---
- name: Create a Docker volume for the ZooKeeper data
  shell: "docker volume create --name {{ zookeeper_volume_name }}"
  become: yes

- name: Create the directory for the ZooKeeper config files
  file:
    path: "{{ zookeeper_host_config_dir }}"
    state: directory
    mode: 0755
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    recurse: yes
  become: yes

- name: Find all the ZooKeeper machines
  register: zk_machines
  ec2_remote_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      instance-state-name: running
      dns_name: "{{ item }}"
  with_items: "{{ groups['zookeeper'] }}"
  run_once: yes
  delegate_to: localhost

- name: Bind the ZooKeeper private IPs
  set_fact:
    zk_addresses: "{{ zk_machines['results'] | map(attribute='instances') | list | private_addresses }}"

- name: Set my ZooKeeper server ID
  set_fact:
    my_id: "{{ zk_addresses | natural_index_of(private_ip) }}"

- name: Move the myid file to the host
  template:
    src: templates/myid.j2
    dest: "{{ zookeeper_host_config_dir }}/myid"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0555

- name: Move the configuration.xsl file to the host
  template:
    src: templates/configuration.xsl
    dest: "{{ zookeeper_host_config_dir }}/configuration.xsl"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0555

- name: Move the log4j file to the host
  template:
    src: templates/log4j.properties
    dest: "{{ zookeeper_host_config_dir }}/log4j.properties"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0555

- name: Move the zoo.cfg file to the host
  template:
    src: templates/zoo.cfg.j2
    dest: "{{ zookeeper_host_config_dir }}/zoo.cfg"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0555

- name: Run the ZooKeeper container
  docker:
    name: "{{ zookeeper_container_name }}"
    image: "{{ zookeeper_docker_image }}"
    detach: yes
    state: reloaded
    restart_policy: always
    restart_policy_retry: 128
    net: host
    volumes:
      - "{{ zookeeper_volume_name }}:{{ zookeeper_data_dir }}"
      - "{{ zookeeper_host_config_dir }}/myid:{{ zookeeper_data_dir }}/myid"
      - "{{ zookeeper_host_config_dir }}:{{ zookeeper_container_config_dir }}"

- name: Wait for ZooKeeper server to come up
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ zookeeper_client_host_port }}"
    delay: 0
    timeout: 60
  delegate_to: "{{ item }}"
  with_items:
    - "{{ inventory_hostname }}"

- name: Export a ZooKeeper connection string for downstream use
  set_fact:
    zk_conn_str: "{{ (zk_addresses | join(':' ~ zookeeper_client_host_port ~ ',')) }}"